export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_REGISTER_BOOL = 'SET_REGISTER_BOOL';
export const SET_CANDIDATE_DATA = 'SET_CANDIDATE_DATA';
export const SET_VOTER_DATA = 'SET_VOTER_DATA';
